name: Cart

on:
  push:
    branches:
      - master
    paths:
      - '**.js'  # Only trigger on changes to Python files (**.py)
      - '.github/workflows/cart.yaml'  # Include workflow file changes

  pull_request:
    branches:
      - master
    paths:
      - '**.js'  # Only trigger on changes to Python files (**.py)
      - '.github/workflows/cart.yaml'  # Include workflow file changes


jobs:
  payment:
    name: Build and deploy cart microservice
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cart

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: NPM install
        run: npm install

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/cart:latest .

      - name: Docker Login (use secrets)
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Docker Push
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cart:latest