name: Catalogue

on:
  push:
    branches:
      - master
    paths:
      - 'catalogue/**'  # Only trigger on changes to catalogue microservice files
      - '.github/workflows/catalogue.yaml'  # Include workflow file changes

  pull_request:
    branches:
      - master
    paths:
      - 'catalogue/**'  # Only trigger a PR raise to catalogue microservice files
      - '.github/workflows/catalogue.yaml'  # Include workflow file changes

jobs:
  catalogue:
    name: Build and deploy catalogue microservice
    runs-on: ubuntu-latest  # standard runner
    defaults:
      run:
        working-directory: catalogue

    steps:
      - name: Checkout code 
        uses: actions/checkout@v7
        

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/catalogue:${{ github.run_number }} .  # Build image tagged as 'catalogue' from current directory

      - name: Docker Login (use secrets)
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Push
        run: |
          docker push ${{secrets.DOCKERHUB_USERNAME}}/catalogue:${{ github.run_number }}