name: shipping

on:
  push:
    branches:
      - master
    paths:
      - '**.java'  # Only trigger on changes to java files (*.java)
      - '.github/workflows/shipping.yaml'  # Include workflow file changes

  pull_request:
    branches:
      - master
    paths:
      - '**.java'  # Only trigger PR Raise on  java files (*.java)
      - '.github/workflows/shipping.yaml'  # Include workflow file changes

jobs:
  shipping:
    name: Build and deploy shipping microservice
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v7

      - name: Build Docker image
        run: |
          docker build -t ${{secrets.DOCKERHUB_USERNAME}}/shipping:${{ github.run_number}}

      - name: Docker Login (use secrets)
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Push
        run: |
          docker push ${{secrets.DOCKERHUB_USERNAME}}/shipping:${{ github.run_number}}