name: User

on:
  push:
    branches:
      - master
    paths:
      - 'user/**'  # Only trigger on changes to Python files (**.py)
      - '.github/workflows/user.yaml'  # Include workflow file changes
      - '.github/workflows/user.yaml'  # Include workflow file changes

  pull_request:
    branches:
      - master
    paths:
      - 'user/**'  # Only trigger on changes to Python files (**.py)
      - '.github/workflows/user.yaml'  # Include workflow file changes

jobs:
  user:
    name: Build and deploy user microservice
    runs-on: ubuntu-latest  
    defaults:
      run:
        working-directory: user

    steps:
      - name: Checkout code 
        uses: actions/checkout@v7

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/user:${{ github.run_number }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/user:latest .

      - name: Docker Login (use secrets)
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Push
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/user:${{ github.run_number }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/user:latest